### ISSUE TITLE
code err

### ISSUE THREAD

**Issue by maxming2333** [okunishinishi/node-filecopy#2]
![image](https://cloud.githubusercontent.com/assets/8816730/18079893/952fb1e0-6ec5-11e6-9826-9d2adb3b4331.png)

I have never seen such a bad error

:(

**Comment by maxming2333** [comment]
can use node 4.x.x ?

**Comment by okunishinishi** [comment]
@maxming2333 

Sorry, supports only node 6.x or later

https://github.com/okunishinishi/node-filecopy/blob/master/package.json#L40
