### ISSUE TITLE
Error: Cannot find module 'co'

### ISSUE THREAD

**Issue by marc-ed-raffalli** [okunishinishi/node-filecopy#3]
Hello,

Just installed latest filecopy (v4) using NPM and I get `Error: Cannot find module 'co'`.
The error does not occur on v3

I can see the module required in files like `filecopy/lib/filing/file_size.js` but `co` is not listed in `filecopy/package.json`.

Did I miss anything? Let me know if you need any additional info

```
npm -v
5.6.0
node -v
v8.9.1
```

**Comment by okunishinishi** [comment]
sorry, this is a bug. i'll fix it
